upgrade alb-sdk to 22-1-3
vmware/global-load-balancing-services-for-kubernetes pull request #213
Opened 2023-08-07 04:47 UTC by arihantg

2023-08-07 04:47 UTC, Dhivyaaj commented
No JIRA Ids found for the PR. Jira id is mandatory to update fix version in jira.                                            Please update respective Jira id in PR title or commit message                                            if the PR is intented for default branches of repo.                                            For mandatory exemptions, comment trigger phrase 'skip jira-id-check' in PR.                                            For manual trigger, comment trigger phrase 'run jira-id-check' in PR.

2023-08-07 05:10 UTC, arihantg commented
build amko

2023-08-07 05:22 UTC, arihantg commented
build amko

2023-08-07 12:40 UTC, swathinsankaran commented
@arihantg could you please add jira id to the title?

2023-08-07 12:47 UTC, swathinsankaran commented on go.mod
> +	github.com/vmware/alb-sdk v0.0.0-20230628102904-861ce312a6bf
this version seems to be different from what is present in Ako.

2023-08-10 11:08 UTC, swathinsankaran commented on go.mod
> +	github.com/vmware/alb-sdk v0.0.0-20230628102904-861ce312a6bf
got it.

2023-08-10 11:11 UTC, swathinsankaran approved these changes
LGTM.
we have to run sanity with this image to ensure it is not breaking anything.

2023-08-17 09:01 UTC, Dhivyaaj commented
No JIRA Ids found for the PR. Jira id is mandatory to update fix version in jira.                                            Please update respective Jira id in PR title or commit message                                            if the PR is intented for default branches of repo.                                            For mandatory exemptions, comment trigger phrase 'skip jira-id-check' in PR.                                            For manual trigger, comment trigger phrase 'run jira-id-check' in PR.

2023-08-17 12:02 UTC, swathinsankaran requested changes
@arihantg Golangci-lint is failing. Please check.

2023-08-17 12:48 UTC, arihantg commented
build amko

2023-08-17 15:09 UTC, swathinsankaran approved these changes

2023-08-18 06:13 UTC, swathinsankaran commented
could you please attach the FT results.

2023-08-21 04:14 UTC, arihantg commented
```
**********************************************************************************************************************************
*                                          AviTest Test Cases Execution Summary Report                                           *
**********************************************************************************************************************************
+----------------------------------------------------------------------------------+----------------+---------------------+-------------+-------------+
| Absolute Path:Test case                                                          |     Results    |       Duration      |  Start Time |   End Time  |
+----------------------------------------------------------------------------------+----------------+---------------------+-------------+-------------+
|      Test Suite Path and Name : test/avitest/functional/amko/test_host_rule.py   |                |                     |             |             |
| ++++++++++++++++++++++++++++++++++++++++                                         |                |                     |             |             |
| TestHostRule.test_reset_amko                                                     |     PASSED     |       00:00:10      |   12:09:54  |   12:10:04  |
| TestHostRule.test_create_apps                                                    |     PASSED     |       00:00:11      |   12:10:04  |   12:10:16  |
| TestHostRule.test_create_hr                                                      |     PASSED     |       00:00:20      |   12:10:16  |   12:10:37  |
| TestHostRule.test_remove_aliases                                                 |     PASSED     |       00:00:20      |   12:10:37  |   12:10:58  |
| TestHostRule.test_update_aliases                                                 |     PASSED     |       00:00:20      |   12:10:58  |   12:11:19  |
| TestHostRule.test_update_duplicate_aliases_in_cluster                            |     PASSED     |       00:00:20      |   12:11:19  |   12:11:40  |
| TestHostRule.test_update_duplicate_aliases_across_cluster                        |     PASSED     |       00:00:21      |   12:11:40  |   12:12:01  |
| TestHostRule.test_delete_duplicate_aliases_in_cluster                            |     PASSED     |       00:00:10      |   12:12:01  |   12:12:11  |
| TestHostRule.test_delete_duplicate_aliases_across_cluster                        |     PASSED     |       00:00:20      |   12:12:11  |   12:12:32  |
| TestHostRule.test_cleanup                                                        |     PASSED     |       00:00:50      |   12:12:32  |   12:13:22  |
| -------------------------------------------------------------------------------- |  ------------  |     -----------     | ----------- | ----------- |
|                                                                                  |   Passed: 10   |                     |             |             |
|                                                                                  |    Failed:0    |                     |             |             |
|  Total test cases: 10                                                            |    Skipped:0   | Total Time:00:03:28 |             |             |
+----------------------------------------------------------------------------------+----------------+---------------------+-------------+-------------+**********************************************************************************************************************************
*                                          AviTest Test Cases Execution Summary Report                                           *
**********************************************************************************************************************************
+----------------------------------------------------------------------------------+----------------+---------------------+-------------+-------------+
| Absolute Path:Test case                                                          |     Results    |       Duration      |  Start Time |   End Time  |
+----------------------------------------------------------------------------------+----------------+---------------------+-------------+-------------+
|      Test Suite Path and Name :                                                  |                |                     |             |             |
| test/avitest/functional/amko/test_amko_gslb_config.py                            |                |                     |             |             |
| ++++++++++++++++++++++++++++++++++++++++                                         |                |                     |             |             |
| TestGslbConfig.test_default_gslb_config                                          |     PASSED     |       00:00:26      |   10:15:14  |   10:15:40  |
| TestGslbConfig.test_add_duplicate_gslb_config                                    |     PASSED     |       00:00:10      |   10:15:40  |   10:15:50  |
| TestGslbConfig.test_wrong_secret_object                                          |     PASSED     |       00:00:00      |   10:15:50  |   10:15:51  |
| TestGslbConfig.test_log_level_accepted                                           |     PASSED     |       00:00:20      |   10:15:51  |   10:16:11  |
| TestGslbConfig.test_cleanup_config                                               |     PASSED     |       00:00:00      |   10:16:11  |   10:16:11  |
| -------------------------------------------------------------------------------- |  ------------  |     -----------     | ----------- | ----------- |
|                                                                                  |    Passed: 5   |                     |             |             |
|                                                                                  |    Failed:0    |                     |             |             |
|  Total test cases: 5                                                             |    Skipped:0   | Total Time:00:00:57 |             |             |
+----------------------------------------------------------------------------------+----------------+---------------------+-------------+-------------+
[2023-08-18 10:18:51] :INFO: [logger_utils timed:58] calc_exc_time: 'display_summary' - 0.01 sec
Rebot framework is generating html file...

**********************************************************************************************************************************
*                                          AviTest Test Cases Execution Summary Report                                           *
**********************************************************************************************************************************
+----------------------------------------------------------------------------------+----------------+---------------------+-------------+-------------+
| Absolute Path:Test case                                                          |     Results    |       Duration      |  Start Time |   End Time  |
+----------------------------------------------------------------------------------+----------------+---------------------+-------------+-------------+
|      Test Suite Path and Name :                                                  |                |                     |             |             |
| test/avitest/functional/amko/test_amko_pool_priority.py                          |                |                     |             |             |
| ++++++++++++++++++++++++++++++++++++++++                                         |                |                     |             |             |
| TestAmkoPoolPriority.test_create_gdp_with_priority                               |     PASSED     |       00:00:22      |   06:04:14  |   06:04:37  |
| TestAmkoPoolPriority.test_update_gdp_with_priority_update                        |     PASSED     |       00:00:10      |   06:04:37  |   0 [...]

2023-08-23 04:27 UTC, merged